# Generated by Django 5.0.4 on 2024-04-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_status_alter_reviews_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlibrary',
            unique_together={('user', 'film')},
        ),
        migrations.AlterUniqueTogether(
            name='userreviews',
            unique_together={('user', 'review')},
        ),
    ]
